# permissions for end users to view clusterscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterscan-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clustermonitor
    app.kubernetes.io/part-of: clustermonitor
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-viewer-role
rules:
- apiGroups:
  - batch.clusterscan.io
  resources:
  - clusterscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.clusterscan.io
  resources:
  - clusterscans/status
  verbs:
  - get
